eureka:
  instance:
    hostname: eureka1 #主机名，集群中区分不同服务器
  client:
    register-with-eureka: true #profile的配置会覆盖公用配置
    fetch-registry: true #profile的配置会覆盖公用配置

    # 1要连接2
    service-url:
      defaultZone: http://eureka2:2002/eureka  #eureka1启动时向eureka2注册
